#!/bin/bash

set -ex

email=$1

# Get a $5 droplet from Digital Ocean
# ssh in with root
# git clone https://github.com/edkins/dank.git
# cd dank/lkb6
# ./install

add-apt-repository ppa:certbot/certbot
apt update
apt upgrade
apt install certbot
apt install nginx
apt install python3-pip
pip3 install --upgrade pip
pip3 install jsonschema

cp ./opendank-http /etc/nginx/sites-available/opendank
ln -s /etc/nginx/sites-available/opendank /etc/nginx/sites-enabled/opendank
rm /etc/nginx/sites-enabled/default

mkdir -p /var/www/opendank
cp -r ./www/* /var/www/opendank

nginx -s reload

certbot certonly -n --webroot -w /var/www/opendank -d opendank.org -d www.opendank.org -d api.opendank.org --agree-tos --email "$email"

cat ./opendank-http ./opendank-https > /etc/nginx/sites-available/opendank
nginx -s reload
